// Generated by Wrangler on Sat Aug 24 2024 17:51:19 GMT+0900 (日本標準時)
// by running `wrangler types`

interface Env {
	AUTH_SECRET: string;
	GOOGLE_CALLBACK_BASE_URL: string;
	GOOGLE_CLIENT_ID: string;
	GOOGLE_CLIENT_SECRET: string;
	DB: D1Database;
}
