import '@/_app/globals.css';
import { Auth0Provider } from '@/_shared/lib/auth0';
import { JotaiProvider } from '@/_shared/lib/jotai';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='ja'>
      <Auth0Provider>
        <JotaiProvider>
          <body>{children}</body>
        </JotaiProvider>
      </Auth0Provider>
    </html>
  );
}
