import { Auth0Provider } from '@/shared/libs/auth0/provider';
import { JotaiProvider } from '@/shared/libs/jotai/provider';
import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='ja'>
      <Auth0Provider>
        <JotaiProvider>
          <body>{children}</body>
        </JotaiProvider>
      </Auth0Provider>
    </html>
  );
}
